-
  name: Chris Fritz
  title: Founder & Programs Director
  bio: I dig helping people learn - and coding things that help people learn. My favorite way of getting to know someone is over a warm cup, so <a href="mailto:chrisvfritz@gmail.com">shoot me an email</a> and you can tell me about <em>your</em> passions.
  tech: A lot of stuff - I like to play! I also love meeting other developers, so if there's something specific you'd like help with, I almost certainly know someone who could help if I can't.
  contact_methods:
    -
      type: GitHub
      body: chrisvfritz
    -
      type: Slack
      body: chrisvfritz
    -
      type: Email
      body: chrisvfritz@gmail.com
  roles:
    - Founder
    - Developer
    - Leader
    - Mentor
-
  name: Katie Fritz
  title: Operations Director
  bio: Over the last 10 years, my career has shifted from public policy to web design and development, with pit stops in IT management and tech consulting.
  tech: I geek project management, content strategy, information architecture, and usability. I'm proficient with HTML and CSS and learning JS and Ruby through Code Lab.
  contact_methods:
    -
      type: GitHub
      body: KatieMFritz
    -
      type: Email
      body: katie@katiemfritz.com
    -
      type: Business
      body: http://katiemfritz.com
    -
      type: LinkedIn
      body: katiemfritz
  roles:
    - Leader
    - Mentor
-
  name: Erik Gillespie
  title: Outreach Director
  bio: Besides my preoccupation with coding and business, I'm also a dad, board gamer, and blogger (I write about all of the above). I love jibber jabbering about all of these, so ask me about one of them some time!
  tech: Java, JavaScript, Node, REST, Inkscape, Gimp, agile concepts, unit testing, application security, yada yada yada.
  contact_methods:
    -
      type: GitHub
      body: egillespie
    -
      type: Email
      body: erik.gillespie@gmail.com
    -
      type: LinkedIn
      body: eriklgillespie
    -
      type: Twitter
      body: eriklgillespie
    -
      type: Business
      body: http://givingjar.org
  roles:
    - Leader
    - Mentor
